name            = input("Nama                   : ")
student_id      = input("NIM                    : ")
Paralel_class   = input("Kelas Paralel          : ")
date_of_birth   = input("Tempat/Tanggal Lahir   : ")
addres          = input("Alamat                 : ")
hobby           = input("Hobby                  : ")
phone_number    = input("No. HP                 : ")

print(f"Nama                    : {name}")
print(f"NIM                     : {student_id}")
print(f"Kelas Paralel           : {Paralel_class}")
print(f"Tempat/Tanggal Lahir    : {date_of_birth}")
print(f"Alamat                  : {addres}")
print(f"Hobby                   : {hobby}")
print(f"No. Hp                  : {phone_number}")